variable "subscriptionId" {
  type     = string
  nullable = false

  description = "The ID of the Azure Subscription containing the Cromwell installation."
}

variable "resourceGroupName" {
  type     = string
  nullable = false

  description = "The name of the Azure Resource Group containing the Cromwell installation."
}

variable "logAnalyticsWorkspaceName" {
  type     = string
  nullable = false

  description = "The name of the Log Analytics Workspace created by the CromwellOnAzure script."
}

variable "virtualNetworkName" {
  type     = string
  nullable = false

  description = "The name of the Azure Virtual Network created by the CromwellOnAzure script."
}

variable "kubernetesClusterName" {
  type     = string
  nullable = false

  description = "The name of the Azure Kubernetes cluster created by the CromwellOnAzure script."
}

variable "cromwellPodSelector" {
  type     = map(string)
  nullable = false
  default  = {
    "io.kompose.service" = "cromwell"
  }

  description = "A map of labels used for selecting the Cromwell Pod generated by the CromwellOnAsure script."
}

variable "kubernetesNamespace" {
  type     = string
  nullable = false
  default  = "coa"

  description = "The kubernetes namespace created by the CromwellOnAzure script, in which Cromwell is deployed."
}

variable "storageAccountName" {
  type     = string
  nullable = false

  description = "The name of the Azure Storage Account generated by the CromwellOnAzure script."
}

variable "cromwellExecutionsStorageContainerName" {
  type     = string
  nullable = false
  default  = "cromwell-executions"

  description = "The name of the Azure Storage Container used for Cromwell execution logs (generated by the CromwellOnAzure script)."
}

variable "subnetIpMask" {
  type    = string
  default = "10.1.2.0/23"

  description = "The IP/mask for a new subnet for the generated Azure Container App. Only change this if you have encounter problems with the default."
}

variable "prefix" {
  type     = string
  nullable = false
  default  = "coa"

  description = "The prefix used in names of resources generated by this Terraform configuration. Defaults to 'coa'."
}

variable "additional_buckets" {
  description = "Additional Azure storage accounts to add to the policy"
  type = list(object({
    name              = string
    resource_group    = string
  }))
  default = []
  nullable = true
}

variable "resourceProviders" {
  type = list(string)
  default = ["Microsoft.ServiceBus", "Microsoft.KeyVault"]
  description = "A list of names of the Azure Resource Providers to register."
}